# Generated by Django 4.2 on 2023-04-16 18:38

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accrediation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                ("short_name", models.CharField(max_length=250)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("India", "India"),
                            ("United Kindom", "United Kindom"),
                            ("Australia", "Australia"),
                            ("United States", "United States"),
                            ("Canada", "Canada"),
                            ("France", "France"),
                            ("Germany", "Germany"),
                        ],
                        default="India",
                        max_length=250,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                ("description", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "gender_accepted",
                    models.CharField(
                        choices=[
                            ("Co-Ed", "Co-Ed"),
                            ("Male", "Male"),
                            ("Female", "Female"),
                        ],
                        default="Co-Ed",
                        max_length=250,
                    ),
                ),
                (
                    "college_type",
                    models.CharField(
                        choices=[("College", "College"), ("University", "University")],
                        default="College",
                        max_length=250,
                    ),
                ),
                ("affiliated", models.CharField(max_length=250)),
                ("accrediation_grade", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=250)),
                ("state", models.CharField(max_length=250)),
                ("city", models.CharField(max_length=250)),
                ("address", models.CharField(max_length=250)),
                (
                    "contact",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(50)],
                    ),
                ),
                (
                    "contact1",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(50)],
                    ),
                ),
                (
                    "accrediation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="college.accrediation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("facility", models.ManyToManyField(to="college.facility")),
            ],
            options={"abstract": False,},
        ),
    ]
