# Generated by Django 4.2 on 2023-05-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="affiliated_type",
            field=models.CharField(
                choices=[
                    ("Autonomous", "Autonomous"),
                    ("Non-Autonomous", "Non-Autonomous"),
                ],
                max_length=250,
                null=True,
            ),
        ),
    ]
