# Generated by Django 4.2 on 2023-05-12 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0002_newsletter_college_image_usnews_timesofindia_qs_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("short_name", models.CharField(max_length=250)),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("Engineering", "Engineering"),
                            ("Arts", "Arts"),
                            ("Nursing", "Nursing"),
                            ("Law", "Law"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "degree_role",
                    models.CharField(
                        choices=[
                            ("Bachelor", "Bachelor"),
                            ("Master", "Master"),
                            ("Doctrate", "Doctrate"),
                        ],
                        max_length=250,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="college.degree"
            ),
        ),
    ]
