# Generated by Django 4.2 on 2023-05-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0007_counsellingdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counsellingdata",
            name="number",
            field=models.CharField(max_length=10),
        ),
    ]
