from django.contrib import admin
from . import models

# Register your models here.
admin.site.register(models.Accrediation)
admin.site.register(models.Facility)
admin.site.register(models.College)
admin.site.register(models.Degree)
admin.site.register(models.Stream)
admin.site.register(models.CollegeDegree)
admin.site.register(models.CollegeStream)
admin.site.register(models.CollegeQuestion)
admin.site.register(models.Department)
admin.site.register(models.NewsLetter)
admin.site.register(models.ARIIA)
admin.site.register(models.BusinessToday)
admin.site.register(models.IIRF)
admin.site.register(models.IndiaEducation)
admin.site.register(models.IndianExpress)
admin.site.register(models.IndiaToday)
admin.site.register(models.TimesofIndia)
admin.site.register(models.EconomicTimes)
admin.site.register(models.NIRF)
admin.site.register(models.Outlook) 
admin.site.register(models.MBAUniverse)
admin.site.register(models.QS)